### ISSUE TITLE
tomcat_major_version variable needed in tomcat-memcached role

### ISSUE THREAD

**Issue by Pablo-CC** [SantanderMetGroup/ansible-thredds-cluster#9]
Role: tomcat-memcached

In two default variables of the role _tds\_\major\_version_ needs to be defined previously by installing with either yum or source roles.

- memcached_session_manager_tc_jar: memcached-session-manager-tc **{{ tomcat_major_version }}** -{{ memcached_session_manager_version }}.jar

- memcached_session_manager_tc_url: https://repo1.maven.org/maven2/de/javakaffee/msm/memcached-session-manager-tc **{{ tomcat_major_version }}/** {{ memcached_session_manager_version }}/{{ memcached_session_manag

**Comment by Pablo-CC** [comment]
This is the output of "{{ tomcat_home }}/bin/version.sh:

Using CATALINA_BASE:   /tmp/tomcat
Using CATALINA_HOME:   /tmp/tomcat
Using CATALINA_TMPDIR: /tmp/tomcat/temp
Using JRE_HOME:        /tmp/jdk/jre
Using CLASSPATH:       /tmp/tomcat/bin/bootstrap.jar:/tmp/tomcat/bin/tomcat-juli.jar
**Server version: Apache Tomcat/8.0.42**
Server built:   Mar 8 2017 19:58:16 UTC
Server number:  8.0.42.0
...


So filtering this output and registering it in a variable called tomcat_major_version should do the trick.

**Important note**: To execute this script either the JAVA_HOME or the JRE_HOME environment variable should be defined

**Comment by zequihg50** [comment]
It may be better to use `assert` or `fail` to inform the user that he forgot to:

- Include the tomcat role, which defines required variables
- Define required variables if there is an existing installation of tomcat. The `assert` of `fail` modules should provide information about the required variables of the role.
